kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind

networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  disableDefaultCNI: false
  
nodes:
  
  - role: control-plane
    image: kindest/node:v1.29.1@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 1389
      hostPort: 1389
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 4317
      hostPort: 4317
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 9002
      hostPort: 9002
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 9191
      hostPort: 9191
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 9300
      hostPort: 9300
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 5432
      hostPort: 5432
      listenAddress: "127.0.0.1"
      protocol: TCP
    
  - role: worker
    image: kindest/node:v1.29.1@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144
    
  - role: worker
    image: kindest/node:v1.29.1@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144
    

  - role: worker
    image: kindest/node:v1.29.1@sha256:a0cc28af37cf39b019e2b448c54d1a3f789de32536cb5a5db61a49623e527144
    
