apiVersion: v1
appVersion: 2.6.3
description: Community developed LDAP software
engine: gotpl
home: https://www.openldap.org
icon: https://raw.githubusercontent.com/jp-gouin/helm-openldap/master/logo.png
keywords:
- ldap
- openldap
maintainers:
- email: jcyriac.ctr@kinetica.com
  name: JCyriac
name: openldap
sources:
- https://github.com/kubernetes/charts
version: 2.6.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
    - bitnami-common
    version: 1.x.x
