otel-collector-config: |
  receivers:
    # Make sure to add the otlp receiver.
    # This will open up the receiver on port 4317
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
    syslog:
      tcp:
        listen_address: "0.0.0.0:9601"
      protocol: rfc5424
  processors:
  extensions:
    health_check: {}
    zpages: {}
  exporters:
    prometheus:
      endpoint: 0.0.0.0:8889
      namespace: "kinetica-system"
    logging:
      loglevel: error

  service:
    extensions: [health_check, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [logging]

      metrics:
        receivers: [otlp]
        processors: []
        exporters: [prometheus, logging]

      logs:
        receivers: [syslog]
        processors: []
        exporters: [logging]
