kinetica_cluster_reconciler.yaml: |2-
    Version: v7.1.9.5
    TargetProvider: "on-prem"
    ComponentConfig:
        SystemNamespace: "kinetica-system"
        DBNamespace: "gpudb"
        LDAP:
          IsExternal: false
          Internal:
              Name: "openldap"
              Namespace: "gpudb"
        Nginx:
          Namespace: "kinetica-system"
    KineticaClusterAdminReconcilerConfig:
      Debug: false
    KineticaClusterBackupReconcilerConfig:
      Debug: false
    KineticaClusterGrantReconcilerConfig:
      Debug: false
    KineticaClusterReconcilerConfig:
      Debug: false
      IsSaaS: false
    KineticaClusterRestoreReconcilerConfig:
      Debug: false
    KineticaClusterRoleReconcilerConfig:
      Debug: false
    KineticaClusterScheduleReconcilerConfig:
      Debug: false
    KineticaClusterUpgradeReconcilerConfig:
      Debug: false
    KineticaClusterUserReconcilerConfig:
      Debug: false
    KineticaClusterResourceGroupReconcilerConfig:
        Debug: false
    KineticaClusterSchemaReconcilerConfig:
        Debug: false
